# This file was generated by Appraisal

source "https://rubygems.org"

gem "rails", :github => "rails/rails"
gem "appraisal"
gem "activerecord-jdbcsqlite3-adapter", platform: :jruby
gem "sqlite3", platform: [:ruby, :mswin, :mingw, :x64_mingw]
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw]
gem "bcrypt"
gem "paperclip"
gem "pry"
gem "shoulda-matchers", github: 'thoughtbot/shoulda-matchers', branch: 'rails-5'

gemspec

